/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0 */

#ifndef PB_WOBBLE_PROTOCOL_PB_H_INCLUDED
#define PB_WOBBLE_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MessageTypes {
    MessageTypes_UNDEFINED = 0,
    MessageTypes_OPEN_STREAM = 1,
    MessageTypes_WRITE_FRAME = 2,
    MessageTypes_CLOSE_STREAM = 3,
    MessageTypes_LIST_STREAMS = 4,
    MessageTypes_STREAM_LIST = 5,
    MessageTypes_SUBSCRIBE = 7,
    MessageTypes_UNSUBSCRIBE = 8,
    MessageTypes_PUBLISH_FRAME = 9,
    MessageTypes_QUERY_FRAMES = 10
} MessageTypes;

/* Struct definitions */
typedef struct _ChannelData {
    pb_size_t data_count;
    uint32_t data[256];
} ChannelData;

typedef struct _CloseStream {
    MessageTypes message_type;
} CloseStream;

typedef struct _ListStreams {
    MessageTypes message_type;
} ListStreams;

typedef struct _QueryFrames {
    char name[64];
    int64_t from_timestamp;
    int64_t to_timestamp;
} QueryFrames;

typedef struct _StreamInfo {
    char name[64];
    int32_t alias;
    int32_t channels;
    int32_t frequency;
    int32_t bits;
    int64_t timestamp;
    char description[64];
    pb_size_t channel_descriptions_count;
    char channel_descriptions[4][64];
    int32_t timestamp_precision;
} StreamInfo;

typedef struct _StreamList {
    MessageTypes message_type;
    pb_callback_t streams;
} StreamList;

typedef struct _Subscribe {
    MessageTypes message_type;
    char name[64];
} Subscribe;

typedef struct _UndefinedMessage {
    MessageTypes message_type;
} UndefinedMessage;

typedef struct _Unsubscribe {
    MessageTypes message_type;
    char name[64];
} Unsubscribe;

typedef struct _OpenStream {
    MessageTypes message_type;
    char password[64];
    bool has_info;
    StreamInfo info;
} OpenStream;

typedef struct _PublishFrame {
    MessageTypes message_type;
    int64_t timestamp;
    int32_t offset;
    pb_size_t channels_count;
    ChannelData channels[4];
} PublishFrame;

typedef struct _WriteFrame {
    MessageTypes message_type;
    int32_t alias;
    pb_size_t channels_count;
    ChannelData channels[4];
} WriteFrame;


/* Helper constants for enums */
#define _MessageTypes_MIN MessageTypes_UNDEFINED
#define _MessageTypes_MAX MessageTypes_QUERY_FRAMES
#define _MessageTypes_ARRAYSIZE ((MessageTypes)(MessageTypes_QUERY_FRAMES+1))


/* Initializer values for message structs */
#define UndefinedMessage_init_default            {_MessageTypes_MIN}
#define StreamInfo_init_default                  {"", 0, 0, 0, 0, 0, "", 0, {"", "", "", ""}, 0}
#define OpenStream_init_default                  {_MessageTypes_MIN, "", false, StreamInfo_init_default}
#define ChannelData_init_default                 {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define WriteFrame_init_default                  {_MessageTypes_MIN, 0, 0, {ChannelData_init_default, ChannelData_init_default, ChannelData_init_default, ChannelData_init_default}}
#define CloseStream_init_default                 {_MessageTypes_MIN}
#define ListStreams_init_default                 {_MessageTypes_MIN}
#define StreamList_init_default                  {_MessageTypes_MIN, {{NULL}, NULL}}
#define Subscribe_init_default                   {_MessageTypes_MIN, ""}
#define Unsubscribe_init_default                 {_MessageTypes_MIN, ""}
#define PublishFrame_init_default                {_MessageTypes_MIN, 0, 0, 0, {ChannelData_init_default, ChannelData_init_default, ChannelData_init_default, ChannelData_init_default}}
#define QueryFrames_init_default                 {"", 0, 0}
#define UndefinedMessage_init_zero               {_MessageTypes_MIN}
#define StreamInfo_init_zero                     {"", 0, 0, 0, 0, 0, "", 0, {"", "", "", ""}, 0}
#define OpenStream_init_zero                     {_MessageTypes_MIN, "", false, StreamInfo_init_zero}
#define ChannelData_init_zero                    {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define WriteFrame_init_zero                     {_MessageTypes_MIN, 0, 0, {ChannelData_init_zero, ChannelData_init_zero, ChannelData_init_zero, ChannelData_init_zero}}
#define CloseStream_init_zero                    {_MessageTypes_MIN}
#define ListStreams_init_zero                    {_MessageTypes_MIN}
#define StreamList_init_zero                     {_MessageTypes_MIN, {{NULL}, NULL}}
#define Subscribe_init_zero                      {_MessageTypes_MIN, ""}
#define Unsubscribe_init_zero                    {_MessageTypes_MIN, ""}
#define PublishFrame_init_zero                   {_MessageTypes_MIN, 0, 0, 0, {ChannelData_init_zero, ChannelData_init_zero, ChannelData_init_zero, ChannelData_init_zero}}
#define QueryFrames_init_zero                    {"", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ChannelData_data_tag                     12
#define CloseStream_message_type_tag             1
#define ListStreams_message_type_tag             1
#define QueryFrames_name_tag                     4
#define QueryFrames_from_timestamp_tag           20
#define QueryFrames_to_timestamp_tag             21
#define StreamInfo_name_tag                      4
#define StreamInfo_alias_tag                     6
#define StreamInfo_channels_tag                  7
#define StreamInfo_frequency_tag                 8
#define StreamInfo_bits_tag                      9
#define StreamInfo_timestamp_tag                 13
#define StreamInfo_timestamp_precision_tag       22
#define StreamInfo_description_tag               14
#define StreamInfo_channel_descriptions_tag      15
#define StreamList_message_type_tag              1
#define StreamList_streams_tag                   17
#define Subscribe_message_type_tag               1
#define Subscribe_name_tag                       4
#define UndefinedMessage_message_type_tag        1
#define Unsubscribe_message_type_tag             1
#define Unsubscribe_name_tag                     4
#define OpenStream_message_type_tag              1
#define OpenStream_info_tag                      16
#define OpenStream_password_tag                  5
#define PublishFrame_message_type_tag            1
#define PublishFrame_timestamp_tag               13
#define PublishFrame_offset_tag                  18
#define PublishFrame_channels_tag                19
#define WriteFrame_message_type_tag              1
#define WriteFrame_alias_tag                     6
#define WriteFrame_channels_tag                  19

/* Struct field encoding specification for nanopb */
#define UndefinedMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1)
#define UndefinedMessage_CALLBACK NULL
#define UndefinedMessage_DEFAULT NULL

#define StreamInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              4) \
X(a, STATIC,   SINGULAR, INT32,    alias,             6) \
X(a, STATIC,   SINGULAR, INT32,    channels,          7) \
X(a, STATIC,   SINGULAR, INT32,    frequency,         8) \
X(a, STATIC,   SINGULAR, INT32,    bits,              9) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,        13) \
X(a, STATIC,   SINGULAR, STRING,   description,      14) \
X(a, STATIC,   REPEATED, STRING,   channel_descriptions,  15) \
X(a, STATIC,   SINGULAR, INT32,    timestamp_precision,  22)
#define StreamInfo_CALLBACK NULL
#define StreamInfo_DEFAULT NULL

#define OpenStream_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1) \
X(a, STATIC,   SINGULAR, STRING,   password,          5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,             16)
#define OpenStream_CALLBACK NULL
#define OpenStream_DEFAULT NULL
#define OpenStream_info_MSGTYPE StreamInfo

#define ChannelData_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   data,             12)
#define ChannelData_CALLBACK NULL
#define ChannelData_DEFAULT NULL

#define WriteFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1) \
X(a, STATIC,   SINGULAR, INT32,    alias,             6) \
X(a, STATIC,   REPEATED, MESSAGE,  channels,         19)
#define WriteFrame_CALLBACK NULL
#define WriteFrame_DEFAULT NULL
#define WriteFrame_channels_MSGTYPE ChannelData

#define CloseStream_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1)
#define CloseStream_CALLBACK NULL
#define CloseStream_DEFAULT NULL

#define ListStreams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1)
#define ListStreams_CALLBACK NULL
#define ListStreams_DEFAULT NULL

#define StreamList_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1) \
X(a, CALLBACK, REPEATED, MESSAGE,  streams,          17)
#define StreamList_CALLBACK pb_default_field_callback
#define StreamList_DEFAULT NULL
#define StreamList_streams_MSGTYPE StreamInfo

#define Subscribe_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1) \
X(a, STATIC,   SINGULAR, STRING,   name,              4)
#define Subscribe_CALLBACK NULL
#define Subscribe_DEFAULT NULL

#define Unsubscribe_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1) \
X(a, STATIC,   SINGULAR, STRING,   name,              4)
#define Unsubscribe_CALLBACK NULL
#define Unsubscribe_DEFAULT NULL

#define PublishFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      1) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,        13) \
X(a, STATIC,   SINGULAR, INT32,    offset,           18) \
X(a, STATIC,   REPEATED, MESSAGE,  channels,         19)
#define PublishFrame_CALLBACK NULL
#define PublishFrame_DEFAULT NULL
#define PublishFrame_channels_MSGTYPE ChannelData

#define QueryFrames_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              4) \
X(a, STATIC,   SINGULAR, INT64,    from_timestamp,   20) \
X(a, STATIC,   SINGULAR, INT64,    to_timestamp,     21)
#define QueryFrames_CALLBACK NULL
#define QueryFrames_DEFAULT NULL

extern const pb_msgdesc_t UndefinedMessage_msg;
extern const pb_msgdesc_t StreamInfo_msg;
extern const pb_msgdesc_t OpenStream_msg;
extern const pb_msgdesc_t ChannelData_msg;
extern const pb_msgdesc_t WriteFrame_msg;
extern const pb_msgdesc_t CloseStream_msg;
extern const pb_msgdesc_t ListStreams_msg;
extern const pb_msgdesc_t StreamList_msg;
extern const pb_msgdesc_t Subscribe_msg;
extern const pb_msgdesc_t Unsubscribe_msg;
extern const pb_msgdesc_t PublishFrame_msg;
extern const pb_msgdesc_t QueryFrames_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UndefinedMessage_fields &UndefinedMessage_msg
#define StreamInfo_fields &StreamInfo_msg
#define OpenStream_fields &OpenStream_msg
#define ChannelData_fields &ChannelData_msg
#define WriteFrame_fields &WriteFrame_msg
#define CloseStream_fields &CloseStream_msg
#define ListStreams_fields &ListStreams_msg
#define StreamList_fields &StreamList_msg
#define Subscribe_fields &Subscribe_msg
#define Unsubscribe_fields &Unsubscribe_msg
#define PublishFrame_fields &PublishFrame_msg
#define QueryFrames_fields &QueryFrames_msg

/* Maximum encoded size of messages (where known) */
#define UndefinedMessage_size                    2
#define StreamInfo_size                          457
#define OpenStream_size                          528
#define ChannelData_size                         1536
#define WriteFrame_size                          6173
#define CloseStream_size                         2
#define ListStreams_size                         2
/* StreamList_size depends on runtime parameters */
#define Subscribe_size                           67
#define Unsubscribe_size                         67
#define PublishFrame_size                        6185
#define QueryFrames_size                         89

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
